/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package export.serializers.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DataSingle extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6299991895809913675L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataSingle\",\"namespace\":\"export.serializers.avro\",\"fields\":[{\"name\":\"rosettaCode\",\"type\":\"string\"},{\"name\":\"metricId\",\"type\":\"string\"},{\"name\":\"vendorMetricId\",\"type\":\"string\"},{\"name\":\"instanceId\",\"type\":\"int\"},{\"name\":\"value\",\"type\":\"float\"},{\"name\":\"timestampNano\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DataSingle> ENCODER =
      new BinaryMessageEncoder<DataSingle>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DataSingle> DECODER =
      new BinaryMessageDecoder<DataSingle>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DataSingle> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DataSingle> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DataSingle>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DataSingle to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DataSingle from a ByteBuffer. */
  public static DataSingle fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence rosettaCode;
  @Deprecated public java.lang.CharSequence metricId;
  @Deprecated public java.lang.CharSequence vendorMetricId;
  @Deprecated public int instanceId;
  @Deprecated public float value;
  @Deprecated public long timestampNano;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DataSingle() {}

  /**
   * All-args constructor.
   * @param rosettaCode The new value for rosettaCode
   * @param metricId The new value for metricId
   * @param vendorMetricId The new value for vendorMetricId
   * @param instanceId The new value for instanceId
   * @param value The new value for value
   * @param timestampNano The new value for timestampNano
   */
  public DataSingle(java.lang.CharSequence rosettaCode, java.lang.CharSequence metricId, java.lang.CharSequence vendorMetricId, java.lang.Integer instanceId, java.lang.Float value, java.lang.Long timestampNano) {
    this.rosettaCode = rosettaCode;
    this.metricId = metricId;
    this.vendorMetricId = vendorMetricId;
    this.instanceId = instanceId;
    this.value = value;
    this.timestampNano = timestampNano;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rosettaCode;
    case 1: return metricId;
    case 2: return vendorMetricId;
    case 3: return instanceId;
    case 4: return value;
    case 5: return timestampNano;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rosettaCode = (java.lang.CharSequence)value$; break;
    case 1: metricId = (java.lang.CharSequence)value$; break;
    case 2: vendorMetricId = (java.lang.CharSequence)value$; break;
    case 3: instanceId = (java.lang.Integer)value$; break;
    case 4: value = (java.lang.Float)value$; break;
    case 5: timestampNano = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'rosettaCode' field.
   * @return The value of the 'rosettaCode' field.
   */
  public java.lang.CharSequence getRosettaCode() {
    return rosettaCode;
  }

  /**
   * Sets the value of the 'rosettaCode' field.
   * @param value the value to set.
   */
  public void setRosettaCode(java.lang.CharSequence value) {
    this.rosettaCode = value;
  }

  /**
   * Gets the value of the 'metricId' field.
   * @return The value of the 'metricId' field.
   */
  public java.lang.CharSequence getMetricId() {
    return metricId;
  }

  /**
   * Sets the value of the 'metricId' field.
   * @param value the value to set.
   */
  public void setMetricId(java.lang.CharSequence value) {
    this.metricId = value;
  }

  /**
   * Gets the value of the 'vendorMetricId' field.
   * @return The value of the 'vendorMetricId' field.
   */
  public java.lang.CharSequence getVendorMetricId() {
    return vendorMetricId;
  }

  /**
   * Sets the value of the 'vendorMetricId' field.
   * @param value the value to set.
   */
  public void setVendorMetricId(java.lang.CharSequence value) {
    this.vendorMetricId = value;
  }

  /**
   * Gets the value of the 'instanceId' field.
   * @return The value of the 'instanceId' field.
   */
  public java.lang.Integer getInstanceId() {
    return instanceId;
  }

  /**
   * Sets the value of the 'instanceId' field.
   * @param value the value to set.
   */
  public void setInstanceId(java.lang.Integer value) {
    this.instanceId = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.Float getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Float value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'timestampNano' field.
   * @return The value of the 'timestampNano' field.
   */
  public java.lang.Long getTimestampNano() {
    return timestampNano;
  }

  /**
   * Sets the value of the 'timestampNano' field.
   * @param value the value to set.
   */
  public void setTimestampNano(java.lang.Long value) {
    this.timestampNano = value;
  }

  /**
   * Creates a new DataSingle RecordBuilder.
   * @return A new DataSingle RecordBuilder
   */
  public static export.serializers.avro.DataSingle.Builder newBuilder() {
    return new export.serializers.avro.DataSingle.Builder();
  }

  /**
   * Creates a new DataSingle RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DataSingle RecordBuilder
   */
  public static export.serializers.avro.DataSingle.Builder newBuilder(export.serializers.avro.DataSingle.Builder other) {
    return new export.serializers.avro.DataSingle.Builder(other);
  }

  /**
   * Creates a new DataSingle RecordBuilder by copying an existing DataSingle instance.
   * @param other The existing instance to copy.
   * @return A new DataSingle RecordBuilder
   */
  public static export.serializers.avro.DataSingle.Builder newBuilder(export.serializers.avro.DataSingle other) {
    return new export.serializers.avro.DataSingle.Builder(other);
  }

  /**
   * RecordBuilder for DataSingle instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataSingle>
    implements org.apache.avro.data.RecordBuilder<DataSingle> {

    private java.lang.CharSequence rosettaCode;
    private java.lang.CharSequence metricId;
    private java.lang.CharSequence vendorMetricId;
    private int instanceId;
    private float value;
    private long timestampNano;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(export.serializers.avro.DataSingle.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rosettaCode)) {
        this.rosettaCode = data().deepCopy(fields()[0].schema(), other.rosettaCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.metricId)) {
        this.metricId = data().deepCopy(fields()[1].schema(), other.metricId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.vendorMetricId)) {
        this.vendorMetricId = data().deepCopy(fields()[2].schema(), other.vendorMetricId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.instanceId)) {
        this.instanceId = data().deepCopy(fields()[3].schema(), other.instanceId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestampNano)) {
        this.timestampNano = data().deepCopy(fields()[5].schema(), other.timestampNano);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DataSingle instance
     * @param other The existing instance to copy.
     */
    private Builder(export.serializers.avro.DataSingle other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.rosettaCode)) {
        this.rosettaCode = data().deepCopy(fields()[0].schema(), other.rosettaCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.metricId)) {
        this.metricId = data().deepCopy(fields()[1].schema(), other.metricId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.vendorMetricId)) {
        this.vendorMetricId = data().deepCopy(fields()[2].schema(), other.vendorMetricId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.instanceId)) {
        this.instanceId = data().deepCopy(fields()[3].schema(), other.instanceId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestampNano)) {
        this.timestampNano = data().deepCopy(fields()[5].schema(), other.timestampNano);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'rosettaCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getRosettaCode() {
      return rosettaCode;
    }

    /**
      * Sets the value of the 'rosettaCode' field.
      * @param value The value of 'rosettaCode'.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder setRosettaCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.rosettaCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rosettaCode' field has been set.
      * @return True if the 'rosettaCode' field has been set, false otherwise.
      */
    public boolean hasRosettaCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rosettaCode' field.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder clearRosettaCode() {
      rosettaCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'metricId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMetricId() {
      return metricId;
    }

    /**
      * Sets the value of the 'metricId' field.
      * @param value The value of 'metricId'.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder setMetricId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.metricId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'metricId' field has been set.
      * @return True if the 'metricId' field has been set, false otherwise.
      */
    public boolean hasMetricId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'metricId' field.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder clearMetricId() {
      metricId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'vendorMetricId' field.
      * @return The value.
      */
    public java.lang.CharSequence getVendorMetricId() {
      return vendorMetricId;
    }

    /**
      * Sets the value of the 'vendorMetricId' field.
      * @param value The value of 'vendorMetricId'.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder setVendorMetricId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.vendorMetricId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'vendorMetricId' field has been set.
      * @return True if the 'vendorMetricId' field has been set, false otherwise.
      */
    public boolean hasVendorMetricId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'vendorMetricId' field.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder clearVendorMetricId() {
      vendorMetricId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'instanceId' field.
      * @return The value.
      */
    public java.lang.Integer getInstanceId() {
      return instanceId;
    }

    /**
      * Sets the value of the 'instanceId' field.
      * @param value The value of 'instanceId'.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder setInstanceId(int value) {
      validate(fields()[3], value);
      this.instanceId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'instanceId' field has been set.
      * @return True if the 'instanceId' field has been set, false otherwise.
      */
    public boolean hasInstanceId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'instanceId' field.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder clearInstanceId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.Float getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder setValue(float value) {
      validate(fields()[4], value);
      this.value = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder clearValue() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestampNano' field.
      * @return The value.
      */
    public java.lang.Long getTimestampNano() {
      return timestampNano;
    }

    /**
      * Sets the value of the 'timestampNano' field.
      * @param value The value of 'timestampNano'.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder setTimestampNano(long value) {
      validate(fields()[5], value);
      this.timestampNano = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestampNano' field has been set.
      * @return True if the 'timestampNano' field has been set, false otherwise.
      */
    public boolean hasTimestampNano() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestampNano' field.
      * @return This builder.
      */
    public export.serializers.avro.DataSingle.Builder clearTimestampNano() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DataSingle build() {
      try {
        DataSingle record = new DataSingle();
        record.rosettaCode = fieldSetFlags()[0] ? this.rosettaCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.metricId = fieldSetFlags()[1] ? this.metricId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.vendorMetricId = fieldSetFlags()[2] ? this.vendorMetricId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.instanceId = fieldSetFlags()[3] ? this.instanceId : (java.lang.Integer) defaultValue(fields()[3]);
        record.value = fieldSetFlags()[4] ? this.value : (java.lang.Float) defaultValue(fields()[4]);
        record.timestampNano = fieldSetFlags()[5] ? this.timestampNano : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DataSingle>
    WRITER$ = (org.apache.avro.io.DatumWriter<DataSingle>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DataSingle>
    READER$ = (org.apache.avro.io.DatumReader<DataSingle>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
